/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SommelierRouteImport } from './routes/sommelier'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapRouteImport } from './routes/map'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AiSommelierRouteImport } from './routes/ai-sommelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReserveIdRouteImport } from './routes/reserve.$id'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as BottleSlugRouteImport } from './routes/bottle.$slug'
import { Route as ApiPublicReservationsNotifyRouteImport } from './routes/api/public/reservations/notify'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SommelierRoute = SommelierRouteImport.update({
  id: '/sommelier',
  path: '/sommelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSommelierRoute = AiSommelierRouteImport.update({
  id: '/ai-sommelier',
  path: '/ai-sommelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveIdRoute = ReserveIdRouteImport.update({
  id: '/reserve/$id',
  path: '/reserve/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BottleSlugRoute = BottleSlugRouteImport.update({
  id: '/bottle/$slug',
  path: '/bottle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReservationsNotifyRoute =
  ApiPublicReservationsNotifyRouteImport.update({
    id: '/api/public/reservations/notify',
    path: '/api/public/reservations/notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-sommelier': typeof AiSommelierRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/games': typeof GamesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shops': typeof ShopsRoute
  '/sommelier': typeof SommelierRoute
  '/terms': typeof TermsRoute
  '/bottle/$slug': typeof BottleSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/api/public/reservations/notify': typeof ApiPublicReservationsNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-sommelier': typeof AiSommelierRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/games': typeof GamesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shops': typeof ShopsRoute
  '/sommelier': typeof SommelierRoute
  '/terms': typeof TermsRoute
  '/bottle/$slug': typeof BottleSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/api/public/reservations/notify': typeof ApiPublicReservationsNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-sommelier': typeof AiSommelierRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/games': typeof GamesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shops': typeof ShopsRoute
  '/sommelier': typeof SommelierRoute
  '/terms': typeof TermsRoute
  '/bottle/$slug': typeof BottleSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/api/public/reservations/notify': typeof ApiPublicReservationsNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-sommelier'
    | '/checkout'
    | '/cookies'
    | '/games'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/shops'
    | '/sommelier'
    | '/terms'
    | '/bottle/$slug'
    | '/business/$slug'
    | '/reserve/$id'
    | '/api/public/reservations/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-sommelier'
    | '/checkout'
    | '/cookies'
    | '/games'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/shops'
    | '/sommelier'
    | '/terms'
    | '/bottle/$slug'
    | '/business/$slug'
    | '/reserve/$id'
    | '/api/public/reservations/notify'
  id:
    | '__root__'
    | '/'
    | '/ai-sommelier'
    | '/checkout'
    | '/cookies'
    | '/games'
    | '/map'
    | '/privacy'
    | '/profile'
    | '/shops'
    | '/sommelier'
    | '/terms'
    | '/bottle/$slug'
    | '/business/$slug'
    | '/reserve/$id'
    | '/api/public/reservations/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSommelierRoute: typeof AiSommelierRoute
  CheckoutRoute: typeof CheckoutRoute
  CookiesRoute: typeof CookiesRoute
  GamesRoute: typeof GamesRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ShopsRoute: typeof ShopsRoute
  SommelierRoute: typeof SommelierRoute
  TermsRoute: typeof TermsRoute
  BottleSlugRoute: typeof BottleSlugRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  ReserveIdRoute: typeof ReserveIdRoute
  ApiPublicReservationsNotifyRoute: typeof ApiPublicReservationsNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sommelier': {
      id: '/sommelier'
      path: '/sommelier'
      fullPath: '/sommelier'
      preLoaderRoute: typeof SommelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sommelier': {
      id: '/ai-sommelier'
      path: '/ai-sommelier'
      fullPath: '/ai-sommelier'
      preLoaderRoute: typeof AiSommelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$id': {
      id: '/reserve/$id'
      path: '/reserve/$id'
      fullPath: '/reserve/$id'
      preLoaderRoute: typeof ReserveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottle/$slug': {
      id: '/bottle/$slug'
      path: '/bottle/$slug'
      fullPath: '/bottle/$slug'
      preLoaderRoute: typeof BottleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reservations/notify': {
      id: '/api/public/reservations/notify'
      path: '/api/public/reservations/notify'
      fullPath: '/api/public/reservations/notify'
      preLoaderRoute: typeof ApiPublicReservationsNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSommelierRoute: AiSommelierRoute,
  CheckoutRoute: CheckoutRoute,
  CookiesRoute: CookiesRoute,
  GamesRoute: GamesRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ShopsRoute: ShopsRoute,
  SommelierRoute: SommelierRoute,
  TermsRoute: TermsRoute,
  BottleSlugRoute: BottleSlugRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  ReserveIdRoute: ReserveIdRoute,
  ApiPublicReservationsNotifyRoute: ApiPublicReservationsNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
